--- #YAML:1.0
name:               B-Lint-StrictOO
version:            0.03
abstract:           Apply strict to classes and methods
author:
    - Josh ben Jore <jjore@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    IPC::Run:  0
requires:
    B::Lint:      1.09
    B::Utils:     0.10
    File::Slurp:  0
    perl:         5.006
resources:
    repository:  http://github.com/gitpan/B-Lint-StrictOO
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
